### ISSUE TITLE
OutboxDispatcherService fault tolerance

### ISSUE THREAD

**Issue by mrozov** [AlexeyRaga/kafkaflow-contrib#13]
Hello!
As far as I can see when the OutboxDispatcherService encounters any exception (db or Kafka may be temporary unavailable) it stops the message processing cycle without any obvious way to recover. Please, correct me if I'm wrong.

I believe a simple try/catch with a delay (configurable) would be a better solution.

**Comment by AlexeyRaga** [comment]
I _think_ that it should bring down the whole application when it crashes? I haven't simulated it, and haven't encountered this situation in the real life yet.

BTW now looking at [AddOutboxDispatcher](https://github.com/AlexeyRaga/kafkaflow-contrib/blob/main/src/Contrib.KafkaFlow.Outbox/ConfigurationExtensions.cs#L25) method I can't really tell why I didn't use `AddHostedService<>` in there...

**Comment by mrozov** [comment]
>I think that it should bring down the whole application when it crashes?
1. I guess it does not :) not 100% sure, but it's very likely.
2. Anyway, when external dependency is unavailable / malfunctioning it may not be resolved by rebooting the pod. So it _may_ be rebooted, but doesn't _have to_.
3. What I do know, is that I saw a table full of records. Pod was rebooted and they were sent. No crashes, no errors in our logs. It's a kind of magic, but not the kind I enjoy.

**Comment by dljaime** [comment]
This seems related to a behaviour I just encountered.

I'm spinning up a new service that uses the Postgres outbox with KafkaFlow.  In my integration tests I use the WebApplicationFactory to run the service and some of my tests involved checking that messages were being emitted to Kafka.  However I was not receiving any events.  Everything else continued worked fine though.

It turned out that there was a race condition between the DB Migration adding the outbox tables to my database and the KafkaFlow outbox running.  Once I made sure the DB Migration always completed first I started reliably seeing messages.

There might be better ways for me to apply my DB Migration in my integration test (they're normally applied during deployment) but it seemed relevant to this post.

**Comment by AlexeyRaga** [comment]
Sad, I would much prefer for it to crash the app.
It may not resolve the issue, of course, or it may, depends on an issue. Crashing the service would also be visible by any alerting/monitoring system, and it'd be the same as crashing the app when any of your "normal" non-outboxed code fails...

I guess we could add the ability to retry with a delay, too. It could be justified by the fact that everyone should monitor/alert on the outbox queue depth anyway...

I need to think about it...
